version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs2023q2-rest-service
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./logs:/home/logs
    restart: on-failure
    networks:
      - homelibrary

  db:
    image: postgres:13
    container_name: homelibrary_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data:cached
    networks:
      - homelibrary

networks:
    homelibrary:
      driver: bridge

